inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Naming/MethodParameterName:
  AllowedNames: ["x", "y", "z"]

RSpec/EmptyLineAfterHook:
  Enabled: false

Style/HashConversion:
  Exclude:
    - spec/**/*_spec.rb

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/smart-validator.rb
